// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TicTacToeML.Model
{
    public class ModelInput
    {
        [ColumnName("TilePlayed"), LoadColumn(0)]
        public string TilePlayed { get; set; }


        [ColumnName("TileID"), LoadColumn(1)]
        public float TileID { get; set; }


        [ColumnName("tile1"), LoadColumn(2)]
        public string Tile1 { get; set; }


        [ColumnName("tile2"), LoadColumn(3)]
        public string Tile2 { get; set; }


        [ColumnName("tile3"), LoadColumn(4)]
        public string Tile3 { get; set; }


        [ColumnName("tile4"), LoadColumn(5)]
        public string Tile4 { get; set; }


        [ColumnName("tile5"), LoadColumn(6)]
        public string Tile5 { get; set; }


        [ColumnName("tile6"), LoadColumn(7)]
        public string Tile6 { get; set; }


        [ColumnName("tile7"), LoadColumn(8)]
        public string Tile7 { get; set; }


        [ColumnName("tile8"), LoadColumn(9)]
        public string Tile8 { get; set; }


        [ColumnName("tile9"), LoadColumn(10)]
        public string Tile9 { get; set; }


    }
}
